### ISSUE TITLE
Preact X compatibility problems?

### ISSUE THREAD

**Issue by lukeundtrug** [laggingreflex/preact-markdown#10]
Hi there, first of all, thanks for the work you put into this! We're currently in the process of upgrading to `Preact X` and noticed that `preact-markdown` doesn't work with version 10.1.0 anymore which is in turn related to `preact-markup` v1.6.0 not functioning with `Preact X`.

So I forked your repo and updated it to utilize `preact-markup` 2.0.0. After doing so I got the following pretty deeply nested error after setState of the parent component was called:

![image](https://user-images.githubusercontent.com/26152379/70807406-c89d5500-1dbd-11ea-8442-8b042820ea9a.png)

From as much as I understand preact, which is admittedly very little, this is thrown because the actual module export in your library gets passed to `createElement` through Preacts `render` function. 
Here: https://github.com/preactjs/preact/blob/1a9d7fcbc2ad46454db5fec6d2583b82b3d6cdad/src/render.js#L23

Do you have any plans on migrating this library to Preact X? I'd be gladly willing to help in any way I can!

**Comment by laggingreflex** [comment]
Fixed. Please upgrade to v2.0.0

**Comment by lukeundtrug** [comment]
Wow, that was quick, thanks a lot! 👍 I guess, the culprit was the default import of preact-markup then, good to know :)
